version: '3'

services:
    nginx:
        image: nginx:1.13
        volumes:
            - ./src:/var/www/html
            - ./cfg/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - NGINX_PORT=80
        depends_on:
            - php

    php:
        build: /php
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html

    mysql:
        image: mysql:8.0   
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d   
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        ports:
            - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql